
import Home from "./page";
import styles from "./styles/page.module.scss";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Home />
  )
}
